name: Update Exchange Rates

on:
  schedule:
    # Her gün saat 15:45'te çalışır (UTC)
    # Türkiye saatiyle 18:45'e denk gelir.
    - cron: '45 15 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies for XML parsing
        run: npm install jsdom

      - name: Fetch and parse XML to JSON
        id: fetch_xml
        run: |
          node -e "
            const { JSDOM } = require('jsdom');
            const fs = require('fs');
            
            const xmlUrl = 'https://tcmb.org.tr/kurlar/today.xml';

            async function fetchAndParse() {
                try {
                    const response = await fetch(xmlUrl);
                    if (!response.ok) {
                        throw new Error(\`Ağ hatası: \${response.status} \${response.statusText}\`);
                    }
                    const xmlData = await response.text();

                    const parser = new JSDOM().window.DOMParser;
                    const xmlDoc = parser.parseFromString(xmlData, 'text/xml');
                    
                    if (xmlDoc.getElementsByTagName('parsererror').length > 0) {
                      throw new Error('XML dosyasında parse hatası.');
                    }

                    const currencies = xmlDoc.getElementsByTagName('Currency');
                    const rates = {};
                    
                    for (const currency of currencies) {
                        const code = currency.getAttribute('CurrencyCode');
                        if (code === 'USD' || code === 'EUR') {
                            rates[code] = {
                                name: currency.getElementsByTagName('Isim')[0].textContent,
                                buying: currency.getElementsByTagName('ForexBuying')[0].textContent,
                                selling: currency.getElementsByTagName('ForexSelling')[0].textContent
                            };
                        }
                    }
                    
                    fs.writeFileSync('data/exchange_rates.json', JSON.stringify(rates, null, 2));
                    console.log('Döviz kurları başarıyla güncellendi!');
                } catch (error) {
                    console.error('Hata:', error);
                    process.exit(1);
                }
            }
            fetchAndParse();
          "

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/exchange_rates.json
          git commit -m "Güncel döviz kurları eklendi." || echo "Değişiklik yok."
          git push